# Generated by Django 5.1.7 on 2025-03-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenized_data', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timestamp for request',
                'verbose_name_plural': 'Timestamps for requests',
                'ordering': ['-created_date'],
            },
        ),
    ]
