# Generated by Django 5.1.7 on 2025-03-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringrequest',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
