# Generated by Django 5.1.7 on 2025-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_scoringrequest_response_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringrequest',
            name='request_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoringrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'В обработке'), ('done', 'Готово')], max_length=255, null=True),
        ),
    ]
